### PR TITLE
Fix fullscreen bug

### LINKED ISSUE #103: Fullscreen sometimes doesn't work
When pressing `F` on a slide, the presentation is supposed to go fullscreen. However, this doesn't always work. This seems to be indicated by the following error in the console:

`Uncaught (in promise) TypeError: Fullscreen request denied
    NuxtJS 46
        Lt
        onDocumentKeyDown
        bind
        We
        tt
        Ue
        Nt
        promise callback*initialize
        setup
        promise callback*setup/</<
        promise callback*setup/<
        Dt
        fr
        lt
        __weh
        Ur
        ul
        promise callback*cl
        Fr
        Gl
        scheduler
        scheduler
        trigger
        Ao
        notify
        trigger
        set value
        E
        Sn
        Sn
        Sn
        Fe
        Qt
        Fe
        resolve
        registerDep
        promise callback*registerDep
        ne
        z
        p
        M
        run
        F
        ne
        z
        p
IL6PhzrQ.js:7:730
`

Edit: This might acutally be a [NEBULA](https://github.com/esciencecenter-digital-skills/NEBULA) problem.

### PR DESCRIPTION
**Pull request by ewan-escience**
### Changes proposed in this pull request

* Call the [reveal.js cleanup function](https://revealjs.com/initialization/#destroy) when slides are unmounted.
* Edit the `.gitignore` to include JetBrains files

**Note:** this was only tested in dev mode.

### How to test

* Run NEBULA against some content, e.g. [Research Software Support](https://github.com/esciencecenter-digital-skills/research-software-support), but I encourage you to test this with other content as well
* Go to a slide page, make it fullscreen (by pressing `F`), exit fullscreen
* Repeat this on other slides
* This should always work
* There should be no errors in the console about fullscreen
* Try this in different browsers

closes #103

### CODE REVIEW

**Review by raar1 — APPROVED** [review]
Good work Ewan! I tested on firefox 145 and chromium 140. Fullscreen works even repeatedly on different slides in different decks. Didn't see any console errors about fullscreen.

File: components/Slides.vue [hunk 1]
```diff
@@ -48,6 +48,8 @@ import RevealNotes from "reveal.js/plugin/notes/notes.js";
 import Search from "reveal.js/plugin/search/search.esm.js";
 import Escience from "escience_theme/escience_5.1.0.esm.js";
 
+const revealRef = ref(null);
```
Comment (OleMussmann) [inline components/Slides.vue:51]: Since we initialize it empty and update it below, should `const` not be a `let` instead?

**Review by OleMussmann — COMMENTED** [review]
I'm unsure about `const` vs `let` here. Happy to approve once we have clarity. In any case, it works well.

File: components/Slides.vue (hunk 1 above)
Comment (ewan-escience) [reply components/Slides.vue:51]: The usage of `const` is correct, as we never reassign the variable `revealRef`, we only mutate the referenced object. If this was incorrect, it would have crashed with an error message.
